name: Publish Docker AMD64 (Manual Test)

on:
  workflow_dispatch:

env:
  REPO: lzw981731/telegram-onedrive
  NAME: L-ING
  EMAIL: lzw981731@gmail.com
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  TAG_NAME: dev-amd64

permissions:
  contents: write

run-name: manual build amd64 dev

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'lzw981731'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ env.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ----------------------------------------------------------------
    # 仅构建 AMD64 环境，不使用 QEMU 模拟，大幅缩短测试时间
    # ----------------------------------------------------------------
    - name: Build and push image (AMD64 ONLY)
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ env.REPO }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Send Notification
      run: |
        curl -X POST -d "title=Github AMD64 Test Completed&body=$GITHUB_REPOSITORY@$TAG_NAME build completed successfully." ${{ secrets.WEBHOOK_URL }}
      continue-on-error: true
